### ISSUE TITLE
Integration With Separate Services (Integração com serviços separados)

### ISSUE THREAD

**Issue by Dezena14** [paulojunior-ufla/piramide-de-teste-pratica#1]
Tradução da seção Integration With Separate Services do artigo [The Practical Test Pyramid](https://martinfowler.com/articles/practical-test-pyramid.html?utm_source=pocket_reader),

**Comment by Dezena14** [comment]
Olá, @paulojunior-ufla eu gostaria de trabalhar nessa seção. Posso?

**Comment by paulojunior-ufla** [comment]
Olá, @Dezena14. Claro, fique à vontade. Aguardo sua contribuição!
