### ISSUE TITLE
Writing Clean Test Code e Putting Tests Into Your Deployment Pipeline

### ISSUE THREAD

**Issue by erick-escape** [paulojunior-ufla/piramide-de-teste-pratica#14]
Meu grupo constituído por Érick de Castro, Layra Vilas Boas, Vítor Ferreira e Vitor Melo pretendendos traduzir essas duas seções do artigo. Como são seções pequenas escolhemos duas. Podemos prosseguir ?

**Comment by paulojunior-ufla** [comment]
Olá, @erick-escape. Podem sim! Obrigado pelo interesse em contribuir.
