### ISSUE TITLE
Conclusion

### ISSUE THREAD

**Issue by Guilherme-Lucas-Vieira** [paulojunior-ufla/piramide-de-teste-pratica#16]
Boa noite.
Pretendo traduzir a seção Conclusion. Posso trabalhar nessa Issue?
Integrante: Guilherme.

**Comment by paulojunior-ufla** [comment]
Olá, @Guilherme-Lucas-Vieira. Que tal incluir também seção _The Confusion About Testing Terminology_. Pode ser?

**Comment by Guilherme-Lucas-Vieira** [comment]
pode ser
