### ISSUE TITLE
Acceptance Tests — Do Your Features Work Correctly?

### ISSUE THREAD

**Issue by luizeduardo7** [paulojunior-ufla/piramide-de-teste-pratica#23]
Tradução da seção Acceptance Tests — Do Your Features Work Correctly? do artigo [The Practical Test Pyramid](https://martinfowler.com/articles/practical-test-pyramid.html?utm_source=pocket_reader)

**Comment by luizeduardo7** [comment]
Gostaria de trabalhar nessa issue.

**Comment by paulojunior-ufla** [comment]
Olá, @luizeduardo7. Pode prosseguir!
