### ISSUE TITLE
User Interface End-to-End Test, Test REST API End-to-End Test e Acceptance Tests — Do Your Features Work Correctly?

### ISSUE THREAD

**Issue by VictorHuggoMoraes** [paulojunior-ufla/piramide-de-teste-pratica#31]
Gostaria de trabalhar na tradução dessas seções

**Comment by paulojunior-ufla** [comment]
Prezado @VictorHuggoMoraes essas seções já foram traduzidas, conforme discussão nas issues do projeto e nos PR abertos.
