### ISSUE TITLE
Contract Tests

### ISSUE THREAD

**Issue by StenioHenrique** [paulojunior-ufla/piramide-de-teste-pratica#4]
Meu grupo deseja (Ademar, Gustavo, Stenio e Vitória) traduzir a seção "Contract Tests" como parte da disciplina GCC259 - Desenvolvimento de Software Livre .

**Comment by paulojunior-ufla** [comment]
Olá, @StenioHenrique. Muito obrigado pelo interesse em contribuir. Aguardo o PR de vocês.
