### ISSUE TITLE
End-to-End Tests

### ISSUE THREAD

**Issue by Nxxxlxs** [paulojunior-ufla/piramide-de-teste-pratica#5]
Olá @paulojunior-ufla, meu grupo (Maria Rita, Matheus Gonçalves e Nicolas de Oliveira) gostaria de trabalhar nessa issue como parte do trabalho da disciplina GCC259. Gostariamos de saber se é necessário também a tradução das subseções do tópico em questão.

**Comment by paulojunior-ufla** [comment]
Olá, @Nxxxlxs. Obrigado pelo interesse em contribuir. Não precisa traduzir as subseções não. Fico aguardando o PR de vocês.
