### ISSUE TITLE
Exploratory Testing

### ISSUE THREAD

**Issue by vitor-tenorio** [paulojunior-ufla/piramide-de-teste-pratica#7]
Boa noite! Meu grupo deseja fazer a tradução da seção "Exploratory Testing"

Integrantes: Iago Manoel, Luis Fernando, Vinícius Caputo e Vitor Tenório

**Comment by vitor-tenorio** [comment]
Boa noite! Meu grupo deseja fazer a tradução da seção "Exploratory Testing"

Integrantes: Iago Manoel, Luis Fernando, Vinícius Caputo e Vitor Tenório

**Comment by paulojunior-ufla** [comment]
Olá, @vitor-tenorio. Combinado! Fico aguardado o PR de vocês.
