### ISSUE TITLE
The Confusion About Testing Terminology

### ISSUE THREAD

**Issue by JulianoA28** [paulojunior-ufla/piramide-de-teste-pratica#9]
Bom dia,
Meu grupo, composto pelo Chrystian, Israel, Luis Wagner e eu iremos nos dividir em duas duplas, sendo uma responsável pela parte da documentação e outra pela parte de código.
O Luis e eu seremos a dupla responsável pela documentação e gostaríamos de fazer a tradução da seção "The Confusion About Testing Terminology".
Obrigado.

**Comment by paulojunior-ufla** [comment]
Olá, @JulianoA28. Ótimo. Podem dar prosseguimento...
